name: fastfoodswitch
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^2.0.1
  firebase_core: any
  firebase_auth: any
  flutter_webview_plugin: any
  cloud_firestore: ^0.13.7
  cupertino_icons: ^0.1.2
  modal_progress_hud: ^0.1.3
  intro_views_flutter: ^2.8.1
  google_maps_flutter: ^0.5.27+3
  geolocator: any
  flutter_bloc: any
  firebase_database: any
  charts_flutter: ^0.9.0
  google_fonts: ^1.1.0
  line_awesome_flutter: any
  google_sign_in: ^4.1.1
  provider: ^3.1.0
  device_info: ^0.4.2+1
  
  flutter_facebook_login: any


dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  fonts:
    - family: Capriola
      fonts:
        - asset: assets/fonts/Capriola/Capriola.ttf
        - asset: assets/fonts/Capriola/Capriola.ttf
          weight: 200


  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/male.png
    - assets/images/female.png



